# Generated by Django 4.1.2 on 2023-10-03 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_vulnerability_closure_date_vulnerability_open_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='External_Project',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='project.project')),
                ('type_of_project', models.CharField(default='External', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='type_of_project',
            field=models.CharField(default='Internal', max_length=20),
        ),
    ]
