# Generated by Django 4.1.2 on 2023-10-17 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_vulnerability_vulnerability_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assignee',
            field=models.CharField(blank=True, default='MPA Cyber Team', max_length=300, null=True),
        ),
    ]
